### PR TITLE
Finetune and bug fix suggestions feature

### LINKED ISSUE #116: [BUG] Fix incorrect suggestion made for command input
# Issue

The refactoring of the commands (in the example below, it is the add command) caused the suggestions to suggest the wrong command

image

## How it happened
The add command has been updated to follow the pattern `add t/<param>` instead of just `add`, so entering `add` on the gui input causes it to jump to to `default` case

```
switch (commandWord) {
        case AddPersonCommand.COMMAND_WORD:
            return new AddPersonCommandParser().parse(arguments);
        ...
        default:
            throw new ParseException(Messages.getSuggestions(commandWord));
```

## Suggested Fix

Update the list of valid commands in `src/main/java/gomedic/commons/core/Messages.java` to hold the new set of commands

### PR DESCRIPTION
**Pull request by ngsengleng**
### Summary

Resolves #116
 
Fixes suggestions displaying outdated suggestions due to modification of command words

### Detail

Suggestions are currently being implemented by making the assumption that there are two parts to erroneous input. If input only has one word we assume user doesn't know which command type to use. If input has two or more words, assume user doesn't know the target of command or it is just garbage input. 

We don't have any expected outputs for users so I don't know what kind of bugs can be caught from this coz its hard to define a definite set of suggestions for each erroneous output.

### Pictures / Gif

assuming user only input one part
Screenshot 2021-10-19 at 2 27 39 PM

assuming user is getting the second part wrong
Screenshot 2021-10-19 at 2 28 13 PM

assuming user gets both parts wrong
Screenshot 2021-10-19 at 2 28 53 PM

assuming user has two parts but is in wrong format

Screenshot 2021-10-19 at 2 29 08 PM
### Checks

- [x] Link PR to issue
- [x] Add Reviewer
- [x] Pass CI

### CODE REVIEW

File: src/test/java/gomedic/commons/core/MessagesTest.java [hunk 1]
```diff
@@ -20,6 +23,23 @@ public void getSuggestions_misspelledCommand_correctSuggestionsReturned() {
...
 
+    @Test
+    public void getSuggestions_misspelledCommandTarget_correctSuggestionsReturned() {
+        String wrongCommand = "add t/patet";
+        List<String> closestWords = List.of(
+                "add t/patient    ",
+                "edit t/patient    ",
+                "add t/doctor    ",
+                "view t/patient    ",
+                "list t/patient    "
```
Comment (radiankrisno) [inline src/test/java/gomedic/commons/core/MessagesTest.java:34]: Why don't the suggestion just return add t/patient here as the first word is correct already and the 2nd work should be closest to t/patient?

**Review by radiankrisno — COMMENTED** [review]
Almost LGTM

File: src/test/java/gomedic/commons/core/MessagesTest.java (hunk 1 above)
Comment (simonjulianl) [reply src/test/java/gomedic/commons/core/MessagesTest.java:34]: Actually yeah as what said, this method is pretty dangerous because `aix t/patient` would return `list t/patient` also, which is not really that close actually but because of the `t/patient` everything becomes "close"

Comment (ngsengleng) [reply src/test/java/gomedic/commons/core/MessagesTest.java:34]: Should i include a check to see if either first or second part of the input string matches any existing suggestion part

Comment (simonjulianl) [reply src/test/java/gomedic/commons/core/MessagesTest.java:34]: Hem I think personally, You can separate the type and the command suggestion, so you do pattern matching for the type part and the command part, and combine them later

**Comment by simonjulianl** [comment]
> the function is still very buggy i have not changed the test cases yet. i forsee a lot of bugs from this feature because we do not have a well-defined function i.e. for each erroneous input we want outputs [1...5]. any comments? sample output Screenshot 2021-10-18 at 2 48 47 PM Screenshot 2021-10-18 at 2 48 55 PM

I am not sure what do you mean by well-defined functions, but my take is 

let's say our typo-ed command is `ade t/doktor` 

* first of all, we can take try to rank and match the first part of the command, `ade` in this case against all possible commands 
e.g. add, edit, delete, list, find, etc and try to put all matching commands into a list (in this case `add t/patient, add t/activity, add t/doctor` into a list) 
* If the second part exists, in this case, `t/doktor`, you try to filter and rank the second part of the command (if doesn't exist, then just filter them out from the list) 
* The total score of each command can be the first part + second part difference (if both part exists), or only the first part (if the second part doesn't exist), for e.g. , if the command is `ade`, then just rank them again `add`, `find`, etc and since add is the closest, put `add t/activity`, `add t/patient` and `add t/doctor` into the list with three of them of score 1
* Then just output the 5 top items from the sorted list by score

File: src/main/java/gomedic/commons/core/Messages.java [hunk 2]
```diff
@@ -33,29 +35,131 @@
...
+                .collect(Collectors.toList());
+    }
+
+    /**
+     * Returns a list of command suggestions based on target.
+     *
+     * @param command Second part of erroneous input.
+     * @param listOfTypes
+     * @param listOfTargets
+     * @return
```
Comment (simonjulianl) [inline src/main/java/gomedic/commons/core/Messages.java:137]: Seems you forgot to add the return here

File: src/main/java/gomedic/commons/core/Messages.java [hunk 3]
```diff
@@ -33,29 +35,131 @@
...
+                "find",
+                "add t/activity",
+                "delete t/activity",
+                "list t/activity",
+                "clear t/activity",
+                "exit");
+        // list of command targets
+        List<String> listOfTargets = Arrays.asList("t/patient", "t/doctor", "t/activity");
+        // get hashset of types for checking
+        HashSet<String> listOfTypes = new HashSet<>(listOfCommands.stream()
```
Comment (simonjulianl) [inline src/main/java/gomedic/commons/core/Messages.java:62]: I am slightly confused why is this called `listOfTypes` even though it contains the commands, and `listOfTargets` contains list of the types

File: src/main/java/gomedic/commons/core/Messages.java [hunk 4]
```diff
@@ -33,29 +35,131 @@
...
+     * @param command Second part of erroneous input.
+     * @param listOfTypes
+     * @param listOfTargets
+     * @return
+     */
+    private static List<String> generateTargetSuggestions(String command, HashSet<String> listOfTypes,
+                                                        List<String> listOfTargets) {
+        List<Pair<Integer, String>> closestStrings;
+        LevenshteinDistance stringChecker = new LevenshteinDistance();
+        HashSet<String> singleWordCommands = new HashSet<>(Arrays.asList("exit", "help"));
```
Comment (simonjulianl) [inline src/main/java/gomedic/commons/core/Messages.java:143]: Actually I think a lot of parts are kind of duplicate with generateTypeSuggestions, but for now I think its fine, we can refine this in v1.4 or if we have time

**Review by simonjulianl — CHANGES_REQUESTED** [review]
Minor changes, also do you have screenshots of the new implementation, from the code it looks fine actually

File: src/main/java/gomedic/commons/core/Messages.java (hunk 3 above)
Comment (ngsengleng) [reply src/main/java/gomedic/commons/core/Messages.java:62]: oh i classified the commands add, delete, edit etc as command types and the kind of data they are accessing like doctors patients etc as targets

File: src/main/java/gomedic/commons/core/Messages.java (hunk 2 above)
Comment (ngsengleng) [reply src/main/java/gomedic/commons/core/Messages.java]: yep ok

File: src/main/java/gomedic/commons/core/Messages.java (hunk 4 above)
Comment (simonjulianl) [reply src/main/java/gomedic/commons/core/Messages.java:143]: Hem, I think is pretty minor we can change it later, thanks man
